server:
  port: 8888

management:
  security:
    enabled: false

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///home/welquer/IdeaProjects/aula_panga/boot-lab/config-repo